log_file: ./data/ccc4prc.log

bigquery:
  pull_request_comments_results_csv_file: ./data/sample/ghtorrent_bigquery_result_20190503_1403_cleaned.csv

machine_learning:
  labeled_seed_excel_file: ../master-of-engineering/Assets/BigQuery/results_20190503_1403_cleaned_classified_manual_labeling.xlsx
  unlabeled_csv_file: ./data/sample/ghtorrent_bigquery_result_20190503_1403_cleaned_dac_classified.csv

dialogue_act_classification:
  classifier_file: ./models/dialogue_act_classifier.pickle
  test_set_percentage: 10 # Percentage of the labeled NPS Chat Corpus to be used as the test dataset (remainder will be the training dataset).
