log_file: ./data/ccc4prc.log

bigquery:
  pull_request_comments_results_csv_file: ./data/sample/ghtorrent_bigquery_result.csv

machine_learning:
  labeled_seed_excel_file:
  unlabeled_csv_file: 

dialogue_act_classification:
  retrain_classifier: False # Whether to train/retrain Dialogue Act Classifier.
  trained_classifier_file: ./data/trained_dialogue_act_classifier.pickle
  test_set_percentage: 10 # Percentage of the labeled NPS Chat Corpus to be used as the test set (remainder will be the train set).
